### ISSUE TITLE
Provide way to style bottom toolbar

### ISSUE THREAD

**Issue by aaronorosen** [Telerik-Verified-Plugins/SafariViewController#2] opened 2016-07-24 23:09 UTC
This is really cool. I was wondering if it is possible to allow the user to style the bottom toolbar? Or would something like that not be possible?  

i.e: here

![image](https://cloud.githubusercontent.com/assets/1063157/17087170/97a370d0-51b8-11e6-9ca2-10cea338b0f5.png)

For example, I'm currently using this: https://github.com/initialxy/cordova-plugin-themeablebrowser but would love to use this instead though the missing feature would be providing a way to style the bottom toolbar with my own images and also provide a hook in order to get callbacks to button presses via javascript.  Would something like this be possible via the SafariViewController?

**Comment by EddyVerbruggen** [comment] 2016-08-12 14:17
Dupe of https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/issues/29

**Closed as completed by EddyVerbruggen** 2016-08-12 14:17 UTC
